// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeeTimeAPI.DbContexts;

#nullable disable

namespace TeeTimeAPI.Migrations
{
    [DbContext(typeof(CourseInfoContext))]
    [Migration("20240823233836_changeDateAndTimeTypeForTeeTime")]
    partial class changeDateAndTimeTypeForTeeTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("TeeTimeAPI.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseURL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "The Links at Terranea",
                            CourseURL = "https://www.terranea.com/golf"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Trump National Golf Club",
                            CourseURL = "https://www.trumpnationallosangeles.com/"
                        });
                });

            modelBuilder.Entity("TeeTimeAPI.Entities.TeeTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("TeeTimes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfPlayer = 4,
                            Price = 200.0,
                            Time = new TimeSpan(0, 10, 30, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfPlayer = 3,
                            Price = 200.0,
                            Time = new TimeSpan(0, 10, 50, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfPlayer = 4,
                            Price = 150.0,
                            Time = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CourseId = 2,
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfPlayer = 4,
                            Price = 150.0,
                            Time = new TimeSpan(0, 11, 20, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CourseId = 2,
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfPlayer = 4,
                            Price = 120.0,
                            Time = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CourseId = 2,
                            Date = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NumberOfPlayer = 2,
                            Price = 100.0,
                            Time = new TimeSpan(2, 2, 50, 0, 0)
                        });
                });

            modelBuilder.Entity("TeeTimeAPI.Entities.TeeTime", b =>
                {
                    b.HasOne("TeeTimeAPI.Entities.Course", "Course")
                        .WithMany("TeeTimes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("TeeTimeAPI.Entities.Course", b =>
                {
                    b.Navigation("TeeTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
